

export const INITIATIVE_STATUS = {
    NEW: "NEW",
    STARTED: "STARTED",
    COMPLETED: "COMPLETED",
    INPROGRESS: "INPROGRESS",
    PAUSED: "PAUSED",
    REJECTED: "REJECTED",
    STOPPED: "STOPPED",
}


export const INITIATIVE_VISIBILITY = {
    PUBLIC: "PUBLIC",
    PRIVATE: "PRIVATE",
    COMPANY: "COMPANY",
}

export const INITIATIVE_ARCHIVED = {
    YES: "YES",
    NO: "NO",
}
